services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    env_file:
        - ./client/.env.production
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.production
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

